name: .NET Core CI/CD Webapp

on:
  push:
    branches: [master, ai]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      build_config: Release

    steps:
    - uses: actions/checkout@v2
      
    - name: Setup .NET Core 3.1.402
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.402
    
    - name: Install dotnet tools
      run: dotnet tool restore
      
    - name: Install dependencies
      run: dotnet restore ./eShopOnWeb.sln
    
    - name: Build
      run: dotnet build ./eShopOnWeb.sln --configuration $build_config --no-restore
    
    - name: Test
      run: dotnet test ./eShopOnWeb.sln --configuration $build_config --no-restore
    
    - name: Publish site
      working-directory: ./src/Web
      run: dotnet publish -c $build_config -o ../../web_publish
    
    - name: Catalog SQL Script
      run: dotnet ef migrations script -c catalogcontext -i -p ./src/Infrastructure/Infrastructure.csproj -s ./src/Web/Web.csproj -o ./scripts/catalog.sql
    
    - name: Identity SQL Script
      run: dotnet ef migrations script -c appidentitydbcontext  -i -p ./src/Infrastructure/Infrastructure.csproj -s ./src/Web/Web.csproj -o ./scripts/identity.sql
    
    - name: Upload web site
      uses: actions/upload-artifact@v2.1.4
      with:
        name: web_site
        path: web_publish
    
    - name: Upload ARM
      uses: actions/upload-artifact@v2
      with:
        name: arm_template
        path: arm
    
    - name: Upload scripts
      uses: actions/upload-artifact@v2
      with:
        name: sql_scripts
        path: ./scripts
  
  deploy:
    needs: build
    runs-on: windows-latest
    steps:
    - name: Download scripts
      uses: actions/download-artifact@v2
      with:
        name: sql_scripts
        path: sql_scripts
    
    - name: Download site
      uses: actions/download-artifact@v2
      with:
        name: web_site
        path: web_site
    
    - name: Download arm
      uses: actions/download-artifact@v2
      with:
        name: arm_template
        path: arm_template
    
    - name: Azure Login
      uses: Azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Deploy Azure Resource Manager (ARM) Template
      uses: Azure/arm-deploy@v1
      with:        
        scope: resourcegroup
        subscriptionId: '${{ secrets.AZURE_SUB_ID }}'        
        resourceGroupName: 'NetCore_GIthubCI_CD_RG'
        template: arm_template/netcore_rg_arm.json       
        deploymentMode: Incremental
        deploymentName: deploy-${{ github.run_id }}
        parameters: sites_netcoregithub_name=netcoregithub sqlserver_password=${{ secrets.DB_PASSWORD }}
     
    - name: Azure WebApp
      uses: Azure/webapps-deploy@v2
      with:
        app-name: netcoregithub      
        package: web_site
    
    - name: Azure App Service Settings
      uses: Azure/appservice-settings@v1
      with:
        app-name: netcoregithub
        connection-strings-json: ${{ secrets.CONNSTRING_JSON }}

    - name: Azure SQL Deploy
      uses: Azure/sql-action@v1
      with:
        server-name: netcoregithub.database.windows.net
        connection-string: ${{ secrets.CATALOG_DB_CONNSTRING }}
        sql-file: sql_scripts/catalog.sql
        
    - name: Azure SQL Deploy
      uses: Azure/sql-action@v1
      with:
        server-name: netcoregithub.database.windows.net
        connection-string: ${{ secrets.IDENTITY_DB_CONNSTRING }}
        sql-file: sql_scripts/identity.sql
