name: .NET Core CI/CD Webapp

on:
  push:
    branches: master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      
    - name: Setup .NET Core 3.1.402
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.402
    
    - name: Install dependencies
      run: dotnet restore ./eShopOnWeb.sln
    
    - name: Build
      run: dotnet build ./eShopOnWeb.sln --configuration Release --no-restore
    
    - name: Test
      run: dotnet test ./eShopOnWeb.sln --configuration Release --no-restore
